---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helloworld-deployment
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - name: nginx-helloworld
        image: machiiine/ngnops:latest
        ports:
        - containerPort: 80
